name: CI/CD Bancop Paraguay
on:
  push:
    branches:
      - QA
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: QA
          token: ${{ secrets.REPO_TOKEN }}

      - name: Build Docker images
        run: |
          docker-compose up -d --build

      - name: Save to images
        run: |
          docker save -o ./login.tar login:latest
          docker save -o ./btw.tar btw:latest
          docker save -o ./account_val.tar account_val:latest
          docker save -o ./transaction_detail.tar transaction_detail:latest
          
      - name: Commit and push changes
        run: |
          git config --global user.name "genderegnan"
          git config --global user.email "andereggenalexis@gmail.com"
          git add *.tar
          git commit -m "Add Images"
          git push origin QA
        
